import pool from '../config/db.js';

/**
 * Model: AI Recommendation Model / Repository
 * Purpose: MySQL query execution for `ai_recommendations` candidate match table.
 * 
 * Data flow:
 * Agent / Reconciliation Service ➔ AI Rec Model ➔ MySQL Pool ➔ `ai_recommendations` table
 */

/**
 * Inserts a new candidate recommendation generated by Groq AI Agent.
 * 
 * Called by:
 * - reconciliationAgent.js
 * 
 * @param {Object} recData - Recommendation object.
 * @param {Object} [connection] - Optional MySQL transaction connection.
 * @returns {Promise<number>} Inserted recommendation ID.
 */
export const insertAIRecommendation = async (recData, connection = null) => {
  const executor = connection || pool;
  const {
    reconciliation_case_id,
    recommended_company_id = null,
    recommended_loan_id = null,
    recommended_schedule_id = null,
    confidence_score,
    reasoning,
    status = 'pending'
  } = recData;

  const query = `
    INSERT INTO ai_recommendations (
      reconciliation_case_id, recommended_company_id,
      recommended_loan_id, recommended_schedule_id, confidence_score,
      reasoning, status
    ) VALUES (?, ?, ?, ?, ?, ?, ?);
  `;

  const [result] = await executor.execute(query, [
    reconciliation_case_id,
    recommended_company_id,
    recommended_loan_id,
    recommended_schedule_id,
    confidence_score,
    reasoning,
    status
  ]);

  return result.insertId;
};

/**
 * Retrieves AI recommendations for a specific reconciliation case ID.
 * 
 * Called by:
 * - reconciliation.service.js
 * 
 * @param {number} caseId - Case ID.
 * @returns {Promise<Array>} List of recommendations with joined entity details.
 */
export const findRecommendationsByCaseId = async (caseId) => {
  const query = `
    SELECT ar.*, 
           c.company_name, c.bank_account_number,
           l.loan_number, l.principal_amount,
           rs.installment_number, rs.due_date, rs.scheduled_amount,
           u.name AS reviewer_name
    FROM ai_recommendations ar
    LEFT JOIN companies c ON ar.recommended_company_id = c.id
    LEFT JOIN loans l ON ar.recommended_loan_id = l.id
    LEFT JOIN repayment_schedules rs ON ar.recommended_schedule_id = rs.id
    LEFT JOIN users u ON ar.reviewed_by = u.id
    WHERE ar.reconciliation_case_id = ?
    ORDER BY ar.created_at DESC;
  `;
  const [rows] = await pool.execute(query, [caseId]);
  return rows;
};

/**
 * Retrieves a single recommendation by primary key ID.
 * 
 * Called by:
 * - reconciliation.service.js
 * 
 * @param {number} recId - Recommendation ID.
 * @returns {Promise<Object|null>} Recommendation details or null.
 */
export const findRecommendationById = async (recId) => {
  const query = `
    SELECT ar.*, 
           c.company_name, c.bank_account_number,
           l.loan_number,
           rs.installment_number, rs.due_date, rs.scheduled_amount, rs.paid_amount,
           p.id AS payment_id, p.amount AS payment_amount, p.transaction_id, p.sender_name
    FROM ai_recommendations ar
    JOIN reconciliation_cases rc ON ar.reconciliation_case_id = rc.id
    JOIN payments p ON rc.payment_id = p.id
    LEFT JOIN companies c ON ar.recommended_company_id = c.id
    LEFT JOIN loans l ON ar.recommended_loan_id = l.id
    LEFT JOIN repayment_schedules rs ON ar.recommended_schedule_id = rs.id
    WHERE ar.id = ?
    LIMIT 1;
  `;
  const [rows] = await pool.execute(query, [recId]);
  return rows.length > 0 ? rows[0] : null;
};
