-- ============================================================
-- FinanceFlow AI — Database Migration
-- Purpose: Create tables for Agent 5, Agent 6, and Settings
-- Run date: 2026-08-20
-- Tables created:
--   1. portfolio_snapshots  (Agent 5 output store)
--   2. notification_alerts  (Agent 6 output store with approval workflow)
--   3. user_settings        (Per-user preferences + admin system settings)
-- ============================================================

-- ------------------------------------------------------------
-- Table 1: portfolio_snapshots
-- Purpose: Stores the output of every Agent 5 (Portfolio Analytics) run.
--          Each row is one full portfolio health snapshot.
-- References: agent_runs.id (BIGINT UNSIGNED) for audit trail
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS portfolio_snapshots (
  id                       BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  agent_run_id             BIGINT UNSIGNED NULL       COMMENT 'References agent_runs.id for full execution audit trail. SET NULL if agent run is purged.',
  run_date                 DATE NOT NULL              COMMENT 'Calendar date this snapshot was computed (DATE only, not timestamp)',
  total_portfolio_value    DECIMAL(15,2) DEFAULT 0    COMMENT 'Sum of outstanding principal across all active loans in rupees',
  collection_efficiency    DECIMAL(5,2) DEFAULT 0     COMMENT 'Percentage of scheduled payments received on-time (0.00 to 100.00)',
  delinquency_rate         DECIMAL(5,2) DEFAULT 0     COMMENT 'Percentage of loans that have at least 1 overdue installment',
  top_borrower_concentration DECIMAL(5,2) DEFAULT 0  COMMENT 'Single largest borrower as % of total portfolio value (concentration risk)',
  total_overdue_amount     DECIMAL(15,2) DEFAULT 0    COMMENT 'Total rupee value currently past due across the entire portfolio',
  active_loan_count        INT DEFAULT 0              COMMENT 'Number of loans in active / disbursed status at snapshot time',
  health_score             INT DEFAULT 0              COMMENT 'AI-computed overall portfolio health score 0 to 100 (higher = healthier)',
  health_grade             VARCHAR(10) DEFAULT 'N/A'  COMMENT 'Human-readable grade: EXCELLENT, GOOD, FAIR, POOR, CRITICAL',
  ai_interpretation        TEXT NULL                  COMMENT 'Groq LLM narrative interpretation of the calculated metrics',
  ai_recommendations       JSON NULL                  COMMENT 'Groq LLM recommended actions as JSON array of strings',
  reasoning_summary        TEXT NULL                  COMMENT 'Short analytical paragraph from Groq explaining the health score',
  groq_model               VARCHAR(100) NULL          COMMENT 'Groq model identifier used for this interpretation step',
  total_tokens_used        INT DEFAULT 0              COMMENT 'Total Groq tokens consumed (prompt + completion) for this snapshot',
  created_at               TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (agent_run_id) REFERENCES agent_runs(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
  COMMENT='Stores portfolio health snapshots generated by Agent 5 (Portfolio Analytics Agent)';


-- ------------------------------------------------------------
-- Table 2: notification_alerts
-- Purpose: Stores SLA breach escalation alerts generated by Agent 6.
--          Each row is one alert for one company/loan with Groq severity + recommendation.
--          Implements human-in-the-loop approval: status can be pending/approved/dismissed.
-- References: agent_runs.id, companies.id, users.id
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS notification_alerts (
  id                   BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  agent_run_id         BIGINT UNSIGNED NULL       COMMENT 'References agent_runs.id for the Agent 6 run that created this alert',
  company_id           INT UNSIGNED NOT NULL      COMMENT 'References companies.id — the borrower with SLA breach',
  loan_id              INT UNSIGNED NULL          COMMENT 'References loans.id — specific loan involved in breach (nullable)',
  repayment_id         INT UNSIGNED NULL          COMMENT 'References repayment_schedules.id — overdue installment (nullable)',
  severity             ENUM('LOW','MEDIUM','HIGH','CRITICAL') NOT NULL DEFAULT 'MEDIUM'
                                                  COMMENT 'Alert severity: determined by Groq after the deterministic SLA engine identifies the breach',
  overdue_days         INT DEFAULT 0              COMMENT 'Calendar days past the repayment due date at time of alert generation',
  outstanding_amount   DECIMAL(15,2) DEFAULT 0    COMMENT 'Total overdue rupee amount for this borrower at time of alert',
  recommended_recipient VARCHAR(255) NULL         COMMENT 'Groq-suggested recipient role e.g. Senior Risk Officer, Finance Manager',
  recommended_action   TEXT NULL                  COMMENT 'Groq-suggested escalation action e.g. Immediate portfolio review',
  ai_reasoning         TEXT NULL                  COMMENT 'Groq reasoning explaining why this severity and recipient were recommended',
  notification_status  ENUM('pending','approved','dismissed') NOT NULL DEFAULT 'pending'
                                                  COMMENT 'Human approval workflow status. pending=awaiting review, approved=action taken, dismissed=no action',
  approved_by          INT UNSIGNED NULL          COMMENT 'References users.id — who approved or dismissed this alert',
  actioned_at          TIMESTAMP NULL             COMMENT 'Timestamp when user approved or dismissed the alert',
  created_at           TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (agent_run_id) REFERENCES agent_runs(id) ON DELETE SET NULL,
  FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
  FOREIGN KEY (approved_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
  COMMENT='Stores escalation alerts from Agent 6 with human-in-the-loop approval workflow';


-- ------------------------------------------------------------
-- Table 3: user_settings
-- Purpose: Stores per-user preferences (theme, notifications) and
--          admin-only system settings (AI thresholds, agent toggles).
-- Design decision: 
--   setting_scope = 'user'   -> personal preference any user can change
--   setting_scope = 'system' -> operational AI settings (admin/super_admin only)
-- References: users.id
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS user_settings (
  id            INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id       INT UNSIGNED NOT NULL              COMMENT 'References users.id — owner of this setting row',
  setting_key   VARCHAR(100) NOT NULL              COMMENT 'Setting identifier. Examples: theme, timezone, notification_email, confidence_threshold, agent_5_enabled',
  setting_value TEXT NOT NULL                      COMMENT 'Setting value stored as string. JSON used for complex values e.g. {"enabled":true,"threshold":85}',
  setting_scope ENUM('user','system') NOT NULL DEFAULT 'user'
                                                   COMMENT 'user = personal preference changeable by any user; system = AI/operational setting restricted to admin/super_admin',
  updated_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_user_setting (user_id, setting_key)  COMMENT 'One row per user per setting key — UPSERT pattern enforced',
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
  COMMENT='Per-user preferences and admin-controlled system/AI operational settings';
