-- =============================================================================
-- Migration 005: Phase 5 Multi-Agent Orchestration & Pipeline Execution State
-- Description: Creates persistent execution history tables for multi-agent workflows,
--              step-by-step telemetry, token attribution, and latency metrics.
-- =============================================================================

-- 1. Pipeline Executions Table (Tracks the macro workflow lifecycle)
CREATE TABLE IF NOT EXISTS pipeline_executions (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    pipeline_name VARCHAR(100) NOT NULL,
    trigger_source ENUM('event_webhook', 'manual_ui', 'scheduled_cron', 'api_direct') NOT NULL DEFAULT 'manual_ui',
    triggered_by INT UNSIGNED NULL,
    status ENUM('queued', 'running', 'completed', 'failed', 'cancelled') NOT NULL DEFAULT 'queued',
    context_data JSON NULL COMMENT 'Initial workflow input parameters, e.g. case_id, company_id, filters',
    correlation_id VARCHAR(64) NULL COMMENT 'Distributed tracing token matching HTTP requests and audit logs',
    total_tokens INT UNSIGNED NOT NULL DEFAULT 0,
    duration_ms INT UNSIGNED NOT NULL DEFAULT 0,
    error_message TEXT NULL,
    started_at TIMESTAMP NULL,
    completed_at TIMESTAMP NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_pipeline_status (status),
    INDEX idx_pipeline_correlation_id (correlation_id),
    INDEX idx_pipeline_created (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 2. Pipeline Steps Table (Tracks granular individual agent execution within a workflow)
CREATE TABLE IF NOT EXISTS pipeline_steps (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    pipeline_id BIGINT UNSIGNED NOT NULL,
    step_index INT UNSIGNED NOT NULL COMMENT 'Sequential step execution index: 1, 2, 3...',
    agent_id INT UNSIGNED NULL COMMENT 'Reference to agents catalog if applicable',
    agent_name VARCHAR(100) NOT NULL COMMENT 'e.g. PaymentReconciliationAgent, RiskAssessmentAgent',
    status ENUM('pending', 'running', 'completed', 'failed', 'skipped') NOT NULL DEFAULT 'pending',
    input_payload JSON NULL COMMENT 'Input context passed to this agent step',
    output_payload JSON NULL COMMENT 'Structured results generated by this agent step',
    tokens_used INT UNSIGNED NOT NULL DEFAULT 0,
    duration_ms INT UNSIGNED NOT NULL DEFAULT 0,
    error_message TEXT NULL,
    started_at TIMESTAMP NULL,
    completed_at TIMESTAMP NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_step_pipeline_id (pipeline_id, step_index),
    INDEX idx_step_status (status),
    CONSTRAINT fk_pipeline_steps_parent
        FOREIGN KEY (pipeline_id) REFERENCES pipeline_executions(id)
        ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
