import React, { useState } from 'react';
import { Zap, Check, X, Loader2, ShieldCheck, AlertCircle } from 'lucide-react';
import { triggerHaptic } from '../../utils/haptics';
import { useOnlineStatus } from '../../hooks/useOnlineStatus';

/**
 * Component: MobileAIActionCard
 * 
 * Purpose:
 *   Mobile-friendly rendering of Phase 3 Action Proposals generated by AI Copilot.
 *   Strictly maintains Human-in-the-Loop confirmation with RBAC and backend audit logging.
 */
export const MobileAIActionCard = ({
  proposal = {},
  onConfirm,
  onDismiss
}) => {
  const { isOnline } = useOnlineStatus();
  const [status, setStatus] = useState(proposal.status || 'pending'); // 'pending' | 'loading' | 'executed' | 'dismissed' | 'failed'
  const [resultMsg, setResultMsg] = useState('');

  const actionTypeLabels = {
    FLAG_CASE: 'Flag Case as Critical',
    ASSIGN_CASE: 'Assign Case to Specialist',
    DRAFT_REMINDER: 'Draft Collection Notice',
    OVERRIDE_MATCH: 'Override Reconciliation Match'
  };

  const handleConfirm = async () => {
    if (!isOnline) {
      triggerHaptic('warning');
      alert('Cannot confirm financial action while offline. An active online backend connection is required.');
      return;
    }

    try {
      setStatus('loading');
      triggerHaptic('light');
      if (onConfirm) {
        await onConfirm(proposal.id);
      }
      setStatus('executed');
      setResultMsg('Action executed successfully and recorded in audit log.');
      triggerHaptic('success');
    } catch (err) {
      setStatus('failed');
      setResultMsg(err.message || 'Execution failed.');
      triggerHaptic('error');
    }
  };

  const handleDismiss = async () => {
    try {
      setStatus('loading');
      triggerHaptic('light');
      if (onDismiss) {
        await onDismiss(proposal.id);
      }
      setStatus('dismissed');
      setResultMsg('Action proposal dismissed.');
    } catch {
      setStatus('dismissed');
    }
  };

  if (status === 'executed') {
    return (
      <div style={{
        background: '#f0fdf4',
        border: '1px solid #bbf7d0',
        borderRadius: '12px',
        padding: '12px 14px',
        display: 'flex',
        alignItems: 'center',
        gap: '8px',
        color: '#166534',
        fontSize: '0.8rem',
        fontWeight: '600'
      }}>
        <ShieldCheck size={16} />
        <span>{resultMsg || 'Action executed and verified.'}</span>
      </div>
    );
  }

  if (status === 'dismissed') {
    return (
      <div style={{
        background: '#f8fafc',
        border: '1px solid #e2e8f0',
        borderRadius: '12px',
        padding: '10px 14px',
        color: '#64748b',
        fontSize: '0.75rem'
      }}>
        Action proposal was dismissed.
      </div>
    );
  }

  return (
    <div style={{
      background: 'linear-gradient(135deg, #fefce8 0%, #fffbeb 100%)',
      border: '1px solid #fde047',
      borderRadius: '14px',
      padding: '14px',
      display: 'flex',
      flexDirection: 'column',
      gap: '10px',
      boxShadow: '0 2px 8px rgba(234, 179, 8, 0.1)'
    }}>
      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '6px', color: '#854d0e', fontSize: '0.75rem', fontWeight: '800' }}>
          <Zap size={14} color="#eab308" />
          <span>ACTION PROPOSAL</span>
        </div>
        <span style={{
          background: '#fef08a',
          color: '#713f12',
          fontSize: '0.65rem',
          fontWeight: '700',
          padding: '2px 6px',
          borderRadius: '4px'
        }}>
          Human Confirmation Required
        </span>
      </div>

      <div>
        <div style={{ fontSize: '0.85rem', fontWeight: '800', color: '#713f12' }}>
          {actionTypeLabels[proposal.action_type] || proposal.action_type || 'Proposed Action'}
        </div>
        <p style={{ fontSize: '0.75rem', color: '#854d0e', marginTop: '2px', lineHeight: 1.3 }}>
          {proposal.reason || 'AI recommendation based on financial ledger analysis.'}
        </p>
      </div>

      {proposal.target_entity && (
        <div style={{
          background: 'rgba(255, 255, 255, 0.7)',
          padding: '6px 10px',
          borderRadius: '8px',
          fontSize: '0.7rem',
          color: '#713f12'
        }}>
          <strong>Target:</strong> {proposal.target_entity} #{proposal.target_id || ''}
        </div>
      )}

      {/* Buttons */}
      <div style={{ display: 'flex', gap: '8px', marginTop: '4px' }}>
        <button
          onClick={handleConfirm}
          disabled={status === 'loading'}
          style={{
            flex: 1,
            background: '#16a34a',
            color: '#ffffff',
            border: 'none',
            padding: '8px 12px',
            borderRadius: '8px',
            fontWeight: '700',
            fontSize: '0.75rem',
            cursor: 'pointer',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            gap: '6px'
          }}
        >
          {status === 'loading' ? <Loader2 size={13} className="animate-spin" /> : <Check size={13} />}
          <span>Confirm Action</span>
        </button>

        <button
          onClick={handleDismiss}
          disabled={status === 'loading'}
          style={{
            background: 'rgba(255, 255, 255, 0.8)',
            border: '1px solid #fde047',
            color: '#854d0e',
            padding: '8px 12px',
            borderRadius: '8px',
            fontWeight: '700',
            fontSize: '0.75rem',
            cursor: 'pointer',
            display: 'flex',
            alignItems: 'center',
            gap: '4px'
          }}
        >
          <X size={13} />
          <span>Dismiss</span>
        </button>
      </div>
    </div>
  );
};

export default MobileAIActionCard;
